#!/usr/bin/env python3
"""Longer propagations for the plot panel's longer spans: links and spacecraft sunlight over a
week, a month, six months or a year (tools/plots.py draws them).

    python tools/longrun.py month|year        propagate and cache (the server does this on demand)

One GMAT run serves several spans and every plot: "month" (30 days at 60 s: Week, Month) and
"year" (365 days at 120 s: 6 months, Year), from the fleet run's time ("now"):
- spacecraft defined by elements start from the fleet run's own GMAT state at now (fleet.json
  objects), propagated with the fleet job's force models (Earth JGM-3 8x8, Moon LP165P 10x10,
  plus the other body and the Sun as point masses);
- TLE spacecraft are propagated with SGP4 from their TLE, but only TLE_DAYS (7) days on: a TLE's
  prediction drifts by kilometres a day, so further on would be fiction;
- OEM spacecraft use their file, where it covers.
GMAT also reports the Sun, the Moon and the Moon's orientation (Mean Earth axes, via
terrain.PA_TO_ME, as the fleet job) on the same grid. Everything is kept in data/long/ as
.npz, one per run kind and fleet run.

The geometry is the fleet job's (find_passes, sun_seen), on whole arrays: a station sees a
spacecraft when it is inside the beam (elevation >= 90 - FOV/2), the Earth / Moon is not in the
way, and, for a Moon station, it is above the terrain horizon at its azimuth.
"""
import json
import math
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from terrain import PA_TO_ME, mask_at  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
LONG_DIR = ROOT / "data" / "long"
FLEET = ROOT / "data" / "fleet.json"
TLE_DIR = ROOT / "tle"
KINDS = {"month": (30, 60), "year": (365, 120)}          # days, step (s)
SPAN_KIND = {"week": "month", "month": "month", "6mo": "year", "year": "year"}
SPAN_DAYS = {"week": 7, "month": 30, "6mo": 182.5, "year": 365}
TLE_DAYS = 7
EARTH_R, MOON_R, SUN_R = 6378.1363, 1737.4, 695700.0


def gmat_time(t):
    return t.strftime("%d %b %Y %H:%M:%S.%f")[:-3]


def fleet_run():
    fleet = json.loads(FLEET.read_text())
    run = datetime.strptime(fleet["generated"], "%d %b %Y %H:%M:%S.%f").replace(tzinfo=timezone.utc)
    return fleet, run


def cache_path(kind, run):
    return LONG_DIR / f"{kind}_{run:%Y%m%d%H%M}.npz"


def state_at(rows, t):
    """The fleet's state (pos, vel) at t (s after the window epoch): rows are on a 60 s grid."""
    best = min(rows, key=lambda r: abs(r["t"] - t))
    if abs(best["t"] - t) > 1e-6:
        raise ValueError(f"no state at t = {t} s in the fleet run")
    return best["pos"], best["vel"]


def tle_epoch(path):
    line1 = [l for l in path.read_text().splitlines() if l.startswith("1 ")][0]
    yy, day = int(line1[18:20]), float(line1[20:32])
    return datetime(2000 + yy if yy < 57 else 1900 + yy, 1, 1, tzinfo=timezone.utc) + timedelta(days=day - 1)


def build(kind):
    """Run GMAT for this kind and fleet run and save the arrays; returns the .npz path."""
    from run_fleet import GMAT_CONSOLE, read_oem
    fleet, run = fleet_run()
    days, step = KINDS[kind]
    end = run + timedelta(days=days)
    LONG_DIR.mkdir(parents=True, exist_ok=True)
    tnow = fleet["generated_t"]
    samples = fleet["moon"]["samples"]
    moon_now = min(samples, key=lambda s: abs(s[0] - tnow))
    s = ["% Generated by tools/longrun.py -- edit that, not this.",
         "Create CoordinateSystem MoonFixed;", "GMAT MoonFixed.Origin = Luna;", "GMAT MoonFixed.Axes = BodyFixed;",
         "Create CoordinateSystem MoonMJ2000Eq;", "GMAT MoonMJ2000Eq.Origin = Luna;", "GMAT MoonMJ2000Eq.Axes = MJ2000Eq;",
         "Create Propagator TLEProp;", "GMAT TLEProp.Type = SPICESGP4;", f"GMAT TLEProp.InitialStepSize = {step};",
         "Create ForceModel FMEarth;", "GMAT FMEarth.CentralBody = Earth;", "GMAT FMEarth.PrimaryBodies = {Earth};",
         "GMAT FMEarth.GravityField.Earth.PotentialFile = 'JGM3.cof';",
         "GMAT FMEarth.GravityField.Earth.Degree = 8;", "GMAT FMEarth.GravityField.Earth.Order = 8;",
         "GMAT FMEarth.PointMasses = {Luna, Sun};",
         "Create ForceModel FMMoon;", "GMAT FMMoon.CentralBody = Luna;", "GMAT FMMoon.PrimaryBodies = {Luna};",
         "GMAT FMMoon.GravityField.Luna.PotentialFile = 'LP165P.cof';",
         "GMAT FMMoon.GravityField.Luna.Degree = 10;", "GMAT FMMoon.GravityField.Luna.Order = 10;",
         "GMAT FMMoon.PointMasses = {Earth, Sun};"]
    for body in ("Earth", "Moon"):
        s += [f"Create Propagator Prop{body};", f"GMAT Prop{body}.FM = FM{body};", f"GMAT Prop{body}.Type = RungeKutta89;",
              f"GMAT Prop{body}.InitialStepSize = 60;", f"GMAT Prop{body}.Accuracy = 1e-11;",
              f"GMAT Prop{body}.MinStep = 0.001;", f"GMAT Prop{body}.MaxStep = {max(60, step)};"]
    # the clock for the frame report: a GEO-sized orbit on fixed steps
    s += ["Create ForceModel FMRef;", "GMAT FMRef.CentralBody = Earth;", "GMAT FMRef.PointMasses = {Earth};",
          "Create Propagator PropRef;", "GMAT PropRef.FM = FMRef;", "GMAT PropRef.Type = RungeKutta89;",
          f"GMAT PropRef.InitialStepSize = {step};", f"GMAT PropRef.MinStep = {step};", f"GMAT PropRef.MaxStep = {step};",
          "GMAT PropRef.Accuracy = 1e-3;",
          "Create Spacecraft Clock;", "GMAT Clock.DateFormat = UTCGregorian;", f"GMAT Clock.Epoch = '{gmat_time(run)}';",
          "GMAT Clock.CoordinateSystem = EarthMJ2000Eq;", "GMAT Clock.DisplayStateType = Keplerian;",
          "GMAT Clock.SMA = 42164;", "GMAT Clock.ECC = 0.001;", "GMAT Clock.INC = 10;",
          "Create ReportFile Frames;", f"GMAT Frames.Filename = '{(LONG_DIR / f'{kind}_frames.csv').as_posix()}';",
          "GMAT Frames.Add = {Clock.ElapsedSecs, Sun.EarthMJ2000Eq.X, Sun.EarthMJ2000Eq.Y, Sun.EarthMJ2000Eq.Z, "
          "Luna.EarthMJ2000Eq.X, Luna.EarthMJ2000Eq.Y, Luna.EarthMJ2000Eq.Z, Earth.MoonFixed.X, Earth.MoonFixed.Y, "
          "Earth.MoonFixed.Z, Sun.MoonFixed.X, Sun.MoonFixed.Y, Sun.MoonFixed.Z};",
          "GMAT Frames.Precision = 16;", "GMAT Frames.WriteHeaders = true;", "GMAT Frames.FixedWidth = false;",
          "GMAT Frames.Delimiter = ',';"]
    props, oem_files, limits, oem_craft = [], {}, {}, []
    for k, (tag, c) in enumerate(fleet["craft"].items()):
        sc = f"SC{k}"
        if c["source"] == "oem":
            oem_craft.append(tag)
            continue
        if c["source"] == "tle":
            path = TLE_DIR / f"{tag}.tle"
            final = min(end, run + timedelta(days=TLE_DAYS))
            limits[tag] = (final - run).total_seconds()
            s += [f"Create Spacecraft {sc};", f"GMAT {sc}.EphemerisName = '{path.as_posix()}';", f"GMAT {sc}.Id = '{tag}';"]
            secs = (final - tle_epoch(path)).total_seconds() + step
            props.append(f"Propagate TLEProp({sc}) {{{sc}.ElapsedSecs = {secs:.3f}}};")
        else:
            pos, vel = state_at(fleet["objects"][tag], tnow)
            final = end
            if c["body"] == "Moon":         # GMAT takes it Moon-centred
                pos = [pos[i] - moon_now[1 + i] for i in range(3)]
                vel = [vel[i] - moon_now[4 + i] for i in range(3)]
            frame = "MoonMJ2000Eq" if c["body"] == "Moon" else "EarthMJ2000Eq"
            s += [f"Create Spacecraft {sc};", f"GMAT {sc}.DateFormat = UTCGregorian;", f"GMAT {sc}.Epoch = '{gmat_time(run)}';",
                  f"GMAT {sc}.CoordinateSystem = {frame};", f"GMAT {sc}.DisplayStateType = Cartesian;"]
            s += [f"GMAT {sc}.{n} = {v!r};" for n, v in zip(("X", "Y", "Z", "VX", "VY", "VZ"), list(pos) + list(vel))]
            props.append(f"Propagate Prop{c['body']}({sc}) {{{sc}.ElapsedSecs = {days * 86400 + step:.3f}}};")
        oem = LONG_DIR / f"{kind}_{tag}.oem"
        oem_files[tag] = oem
        s += [f"Create EphemerisFile E{sc};", f"GMAT E{sc}.Spacecraft = {sc};", f"GMAT E{sc}.Filename = '{oem.as_posix()}';",
              f"GMAT E{sc}.FileFormat = CCSDS-OEM;", f"GMAT E{sc}.EpochFormat = UTCGregorian;",
              f"GMAT E{sc}.InitialEpoch = '{gmat_time(run)}';", f"GMAT E{sc}.FinalEpoch = '{gmat_time(final)}';",
              f"GMAT E{sc}.StepSize = {step};", f"GMAT E{sc}.Interpolator = Lagrange;", f"GMAT E{sc}.InterpolationOrder = 7;",
              f"GMAT E{sc}.CoordinateSystem = EarthMJ2000Eq;", f"GMAT E{sc}.WriteEphemeris = true;"]
    # the frame report would repeat a row on every step of every later propagation: off after the clock
    s += ["BeginMissionSequence;", f"Propagate PropRef(Clock) {{Clock.ElapsedSecs = {days * 86400 + step:.3f}}};",
          "Toggle Frames Off;"] + props
    script = LONG_DIR / f"{kind}.script"
    script.write_text("\n".join(s) + "\n")
    for f in list(oem_files.values()) + [LONG_DIR / f"{kind}_frames.csv"]:
        if f.exists():
            f.unlink()
    proc = subprocess.run([str(GMAT_CONSOLE), "--run", str(script), "--exit"], cwd=Path(GMAT_CONSOLE).parent,
                          capture_output=True, text=True)
    if "successful" not in proc.stdout:
        raise RuntimeError("GMAT long run failed:\n" + proc.stdout[-1500:] + proc.stderr[-1500:])

    # the grid, the frames on it
    t = np.arange(0, days * 86400 + 0.5, step, dtype=np.float64)
    n = len(t)
    rows, seen = [], set()
    for line in (LONG_DIR / f"{kind}_frames.csv").read_text().splitlines()[1:]:
        f = line.split(",")
        if len(f) != 13 or f[0] in seen:
            continue
        seen.add(f[0])
        rows.append([float(v) for v in f])
    a = np.array(sorted(rows))
    idx = np.round(a[:, 0] / step).astype(int)
    keep = (idx >= 0) & (idx < n)
    frames = np.full((n, 12), np.nan)
    frames[idx[keep]] = a[keep, 1:]
    if np.isnan(frames).any():
        raise RuntimeError("the frame report has gaps")
    sun, moon = frames[:, 0:3], frames[:, 3:6]
    earth_mf, sun_mf = frames[:, 6:9] @ PA_TO_ME.T, frames[:, 9:12] @ PA_TO_ME.T
    R = triad(-moon, sun - moon, earth_mf, sun_mf)            # Moon-fixed (ME) -> EarthMJ2000Eq

    pos = {}
    for tag, oem in oem_files.items():
        p = np.full((n, 3), np.nan)
        _, states = read_oem(oem)
        for utc, xyz, _v in states:
            i = int(round((utc - run).total_seconds() / step))
            if 0 <= i < n:
                p[i] = xyz
        pos[tag] = p
    for tag in oem_craft:
        pos[tag] = oem_positions(tag, run, t, moon)
    impacts = {}
    for tag, c in fleet["craft"].items():
        if c["body"] == "Moon" and tag in pos:
            under = np.nonzero(np.linalg.norm(pos[tag] - moon, axis=1) < MOON_R)[0]
            if len(under):                       # it hit the Moon: nothing after that
                impacts[tag] = float(t[under[0]])
                pos[tag][under[0]:] = np.nan
    for f in list(oem_files.values()) + [LONG_DIR / f"{kind}_frames.csv"]:
        f.unlink(missing_ok=True)                # the .npz below keeps what is needed
    out = cache_path(kind, run)
    np.savez_compressed(out, t=t, sun=sun, moon=moon, R=R, run=np.array(run.timestamp()), step=np.array(step),
                        tags=np.array(list(pos)), limits=json.dumps(limits), impacts=json.dumps(impacts),
                        **{f"pos_{i}": pos[tag] for i, tag in enumerate(pos)})
    return out


def oem_positions(tag, run, t, moon):
    """An OEM spacecraft's position on the grid (Earth-centred), cubic Hermite between its
    states; NaN outside what the file covers."""
    from spacecraft import read_oem_file, read_spacecraft
    path = next(c["oem"] for c in read_spacecraft() if c["tag"] == tag)
    p = np.full((len(t), 3), np.nan)
    for seg in read_oem_file(path):
        ts = np.array([(u - run).total_seconds() for u, _, _ in seg["rows"]])
        xs = np.array([x for _, x, _ in seg["rows"]], dtype=float)
        vs = np.array([v for _, _, v in seg["rows"]], dtype=float)
        inside = (t >= ts[0]) & (t <= ts[-1])
        j = np.clip(np.searchsorted(ts, t[inside], side="right") - 1, 0, len(ts) - 2)
        h = ts[j + 1] - ts[j]
        u = ((t[inside] - ts[j]) / h)[:, None]
        h00, h10 = 2 * u ** 3 - 3 * u ** 2 + 1, u ** 3 - 2 * u ** 2 + u
        h01, h11 = -2 * u ** 3 + 3 * u ** 2, u ** 3 - u ** 2
        q = h00 * xs[j] + h10 * h[:, None] * vs[j] + h01 * xs[j + 1] + h11 * h[:, None] * vs[j + 1]
        if seg["center"] == "MOON":
            q = q + moon[inside]
        p[inside] = q
    return p


def triad(a1, a2, b1, b2):
    """R (N x 3 x 3) with R b = a, row by row as run_fleet.triad."""
    def frame(v1, v2):
        x = v1 / np.linalg.norm(v1, axis=1, keepdims=True)
        y = np.cross(v1, v2)
        y /= np.linalg.norm(y, axis=1, keepdims=True)
        return np.stack([x, y, np.cross(x, y)], axis=1)   # rows: the triad's axes
    ta, tb = frame(a1, a2), frame(b1, b2)
    return np.einsum("nki,nkj->nij", ta, tb)


def load(span):
    """The arrays for a span (propagating first if not cached): {t, sun, moon, R, pos: {tag},
    limits: {tag: s}, run, step}, cut to the span."""
    fleet, run = fleet_run()
    kind = SPAN_KIND[span]
    path = cache_path(kind, run)
    if not path.exists():
        build(kind)
    d = np.load(path)
    keep = d["t"] <= SPAN_DAYS[span] * 86400 + 0.5
    pos = {str(tag): d[f"pos_{i}"][keep] for i, tag in enumerate(d["tags"])}
    return {"t": d["t"][keep], "sun": d["sun"][keep], "moon": d["moon"][keep], "R": d["R"][keep], "pos": pos,
            "limits": json.loads(str(d["limits"])), "impacts": json.loads(str(d["impacts"])), "run": run,
            "step": float(d["step"]), "fleet": fleet}


# ---- geometry on arrays (as run_fleet.find_passes / sun_seen) ----

def hits_sphere(a, b, centre, radius):
    d = b - a
    f = a - centre
    dd = np.einsum("ij,ij->i", d, d)
    s = np.clip(-np.einsum("ij,ij->i", f, d) / dd, 0.0, 1.0)
    closest = f + d * s[:, None]
    return np.einsum("ij,ij->i", closest, closest) < radius * radius


def station_view(L, st, tag):
    """(elevation deg, visible bool) of spacecraft tag from ground station st (fleet.json)."""
    fleet, t = L["fleet"], L["t"]
    x = L["pos"][tag]
    lat, lon = math.radians(st["lat"]), math.radians(st["lon"])
    up_f = np.array([math.cos(lat) * math.cos(lon), math.cos(lat) * math.sin(lon), math.sin(lat)])
    east_f = np.array([-math.sin(lon), math.cos(lon), 0.0])
    north_f = np.array([-math.sin(lat) * math.cos(lon), -math.sin(lat) * math.sin(lon), math.cos(lat)])
    site_f = np.array(st["ecef_km"])
    if st.get("body") == "Moon":
        p = L["moon"] + np.einsum("nij,j->ni", L["R"], site_f)
        up = np.einsum("nij,j->ni", L["R"], up_f)
        blocked = hits_sphere(p, x, np.zeros(3), EARTH_R)
    else:
        a = np.radians(fleet["earth"]["rotation_deg"] + fleet["earth"]["rate_deg_per_s"] * (t + fleet["generated_t"]))
        c, s_ = np.cos(a), np.sin(a)
        rot = lambda v: np.stack([c * v[0] - s_ * v[1], s_ * v[0] + c * v[1], np.full_like(a, v[2])], axis=1)
        p, up = rot(site_f), rot(up_f)
        blocked = hits_sphere(p, x, L["moon"], MOON_R)
    d = x - p
    dist = np.linalg.norm(d, axis=1)
    el = np.degrees(np.arcsin(np.clip(np.einsum("ij,ij->i", d, up) / dist, -1, 1)))
    visible = (el >= 90.0 - st["fov_deg"] / 2.0) & ~blocked
    tr = fleet.get("terrain", {}).get("station:" + st["name"])
    if st.get("body") == "Moon" and tr:
        dm = np.einsum("nji,nj->ni", L["R"], d)                 # into the Moon-fixed frame (R transposed)
        az = np.nan_to_num(np.degrees(np.arctan2(dm @ east_f, dm @ north_f)) % 360.0)   # NaN: no position (below)
        visible &= el >= mask_at(np.asarray(tr["mask"]), az)
    visible &= ~np.isnan(x).any(axis=1)
    return el, visible


def disc_overlap(a, b, d):
    """Overlap area of discs of angular radius a, b, d apart (rad), on arrays."""
    out = np.zeros_like(d)
    full = d <= np.abs(a - b)
    out[full] = np.pi * np.minimum(a, b)[full] ** 2
    part = (d < a + b) & ~full
    aa, bb, dd = a[part], b[part], d[part]
    k = np.sqrt(np.maximum((-dd + aa + bb) * (dd + aa - bb) * (dd - aa + bb) * (dd + aa + bb), 0.0))
    out[part] = (aa * aa * np.arccos(np.clip((dd * dd + aa * aa - bb * bb) / (2 * dd * aa), -1, 1))
                 + bb * bb * np.arccos(np.clip((dd * dd + bb * bb - aa * aa) / (2 * dd * bb), -1, 1)) - 0.5 * k)
    return out


def sunlight(L, tag):
    """Share of the Sun's disc seen by the spacecraft past the Earth and the Moon (NaN where it
    has no position)."""
    x = L["pos"][tag]
    ds = L["sun"] - x
    dsn = np.linalg.norm(ds, axis=1)
    a = np.arcsin(SUN_R / dsn)
    seen = np.ones(len(x))
    for centre, radius in ((np.zeros(3), EARTH_R), (L["moon"], MOON_R)):
        db = centre - x
        dbn = np.linalg.norm(db, axis=1)
        b = np.arcsin(np.clip(radius / dbn, -1, 1))
        sep = np.arccos(np.clip(np.einsum("ij,ij->i", ds, db) / (dsn * dbn), -1, 1))
        seen -= disc_overlap(a, b, sep) / (np.pi * a * a)
    seen = np.clip(seen, 0.0, 1.0)
    seen[np.isnan(x).any(axis=1)] = np.nan
    return seen


def earth_clearance(L, tag):
    """The Earth's centre above the Moon's limb (deg) seen from a lunar spacecraft."""
    x = L["pos"][tag]
    de, dm = -x, L["moon"] - x
    den, dmn = np.linalg.norm(de, axis=1), np.linalg.norm(dm, axis=1)
    sep = np.degrees(np.arccos(np.clip(np.einsum("ij,ij->i", de, dm) / (den * dmn), -1, 1)))
    return sep - np.degrees(np.arcsin(np.clip(MOON_R / dmn, -1, 1)))


def binned(L, values, how="mean", bin_s=86400):
    """Per UTC bin (a day, or bin_s seconds from midnight): (the middle of each bin, the mean of
    values, or the hours / minutes of True); NaN for a bin the data covers less than 90 % of
    (a part bin at either end, or past the end of a spacecraft's trajectory)."""
    stamp = L["run"].timestamp() + L["t"]
    b = np.floor(stamp / bin_s).astype(np.int64)
    full = bin_s / L["step"]
    when, out = [], []
    for bval in np.unique(b):
        sel = b == bval
        v = values[sel].astype(float)
        ok = ~np.isnan(v)
        when.append(datetime.fromtimestamp(bval * bin_s + bin_s / 2, tz=timezone.utc))
        if sel.sum() < 0.9 * full or ok.sum() < 0.9 * sel.sum():
            out.append(np.nan)
        elif how == "hours":
            out.append(float(v[ok].sum()) * L["step"] / 3600.0)
        elif how == "minutes":
            out.append(float(v[ok].sum()) * L["step"] / 60.0)
        else:
            out.append(float(v[ok].mean()))
    return when, np.array(out)


if __name__ == "__main__":
    import time
    t0 = time.time()
    print(build(sys.argv[1] if len(sys.argv) > 1 else "month"), f"({time.time() - t0:.1f} s)")
