#!/usr/bin/env python3
"""Fleet job: TLEs -> GMAT (headless) -> CCSDS OEM files -> data/fleet.json for the viewer.

    python tools/run_fleet.py

Reads every tle/*.tle (name line + the two element lines), writes a GMAT script that
propagates each spacecraft from its TLE with GMAT's SGP4 propagator (SPICESGP4) and
writes one CCSDS OEM per spacecraft, runs GmatConsole headless, then merges the OEMs
into data/fleet.json.

The window runs from 1 hour before the run to 12 hours after it, at 60 s steps, so a
late or missed run still leaves hours of track. GMAT converts SGP4's TEME output, so
the OEMs (and the JSON) are in EarthMJ2000Eq, the frame the viewer already uses.

This is the step to schedule (e.g. every 6 hours) once the TLEs are refreshed.
"""
import json
import os
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TLE_DIR = ROOT / "tle"
OEM_DIR = ROOT / "data" / "oem"
SCRIPT = ROOT / "data" / "fleet_run.script"
OUT_JSON = ROOT / "data" / "fleet.json"
GMAT_CONSOLE = Path(os.environ.get("GMAT_CONSOLE", r"F:\gmat-win-R2026a\bin\GmatConsole.exe"))

WINDOW_BEFORE = timedelta(hours=1)
WINDOW_AFTER = timedelta(hours=12)
STEP_SECONDS = 60


def read_tles():
    """Return [(name, catalog_number, tle_path, tle_epoch_utc)] for each tle/*.tle."""
    fleet = []
    for path in sorted(TLE_DIR.glob("*.tle")):
        lines = [l.rstrip() for l in path.read_text().splitlines() if l.strip()]
        if len(lines) != 3 or not lines[1].startswith("1 ") or not lines[2].startswith("2 "):
            sys.exit(f"{path.name}: expected a name line and two element lines")
        for line in lines[1:]:
            digits = sum(int(c) if c.isdigit() else (c == "-") for c in line[:68]) % 10
            if len(line) != 69 or digits != int(line[68]):
                sys.exit(f"{path.name}: bad length or checksum in line {line[0]}")
        name = lines[0].strip()
        catalog = lines[1][2:7].strip()
        yy, day = int(lines[1][18:20]), float(lines[1][20:32])
        epoch = datetime(2000 + yy if yy < 57 else 1900 + yy, 1, 1, tzinfo=timezone.utc) + timedelta(days=day - 1)
        fleet.append((name, catalog, path, epoch))
    if not fleet:
        sys.exit(f"no TLEs in {TLE_DIR}")
    return fleet


def gmat_time(t):
    return t.strftime("%d %b %Y %H:%M:%S.") + f"{t.microsecond // 1000:03d}"


def write_script(fleet, start, end):
    s = ["% Generated by tools/run_fleet.py -- edit that, not this.", ""]
    s += ["Create Propagator TLEProp;",
          "GMAT TLEProp.Type = SPICESGP4;",
          f"GMAT TLEProp.InitialStepSize = {STEP_SECONDS};", ""]
    for name, catalog, path, _ in fleet:
        sc = f"SC{catalog}"
        s += [f"Create Spacecraft {sc};",
              f"GMAT {sc}.EphemerisName = '{path.as_posix()}';",
              f"GMAT {sc}.Id = '{catalog}';",  # must match the TLE's catalog number
              f"Create EphemerisFile OEM{catalog};",
              f"GMAT OEM{catalog}.Spacecraft = {sc};",
              f"GMAT OEM{catalog}.Filename = '{(OEM_DIR / (catalog + '.oem')).as_posix()}';",
              f"GMAT OEM{catalog}.FileFormat = CCSDS-OEM;",
              f"GMAT OEM{catalog}.EpochFormat = UTCGregorian;",
              f"GMAT OEM{catalog}.InitialEpoch = '{gmat_time(start)}';",
              f"GMAT OEM{catalog}.FinalEpoch = '{gmat_time(end)}';",
              f"GMAT OEM{catalog}.StepSize = {STEP_SECONDS};",
              f"GMAT OEM{catalog}.Interpolator = Lagrange;",
              f"GMAT OEM{catalog}.InterpolationOrder = 7;",
              f"GMAT OEM{catalog}.CoordinateSystem = EarthMJ2000Eq;",
              f"GMAT OEM{catalog}.WriteEphemeris = true;", ""]
    s += ["BeginMissionSequence;"]
    # One Propagate per spacecraft: the TLE propagator needs all spacecraft in a
    # Propagate to share an epoch, and each TLE has its own.
    for name, catalog, _, epoch in fleet:
        secs = (end - epoch).total_seconds() + STEP_SECONDS
        s += [f"Propagate TLEProp(SC{catalog}) {{SC{catalog}.ElapsedSecs = {secs:.3f}}};"]
    SCRIPT.write_text("\n".join(s) + "\n")


def read_oem(path):
    """Return (frame, [(utc datetime, [x,y,z], [vx,vy,vz])]) from a CCSDS OEM (km, km/s)."""
    frame, rows, in_data = None, [], False
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("REF_FRAME"):
            frame = line.split("=")[1].strip()
        elif line == "META_STOP":
            in_data = True
        elif line == "META_START":
            in_data = False
        elif in_data and line and not line.startswith("COMMENT"):
            f = line.split()
            t = datetime.fromisoformat(f[0]).replace(tzinfo=timezone.utc)
            rows.append((t, [float(v) for v in f[1:4]], [float(v) for v in f[4:7]]))
    return frame, rows


def main():
    fleet = read_tles()
    now = datetime.now(timezone.utc).replace(second=0, microsecond=0)
    start, end = now - WINDOW_BEFORE, now + WINDOW_AFTER
    for name, catalog, _, epoch in fleet:
        if epoch > start:
            sys.exit(f"{name}: TLE epoch {epoch} is after the window start {start}")
    OEM_DIR.mkdir(parents=True, exist_ok=True)
    for old in OEM_DIR.glob("*.oem"):
        old.unlink()
    write_script(fleet, start, end)

    run = subprocess.run([str(GMAT_CONSOLE), "--run", str(SCRIPT), "--exit"],
                         cwd=GMAT_CONSOLE.parent, capture_output=True, text=True)
    if "successful" not in run.stdout:
        sys.exit("GMAT run failed:\n" + run.stdout[-2000:] + run.stderr[-2000:])

    objects, names = {}, {}
    for name, catalog, _, epoch in fleet:
        frame, rows = read_oem(OEM_DIR / f"{catalog}.oem")
        if frame != "EME2000":
            sys.exit(f"{catalog}.oem: unexpected frame {frame}")
        objects[catalog] = [{"t": round((t - start).total_seconds(), 3), "pos": p, "vel": v}
                            for t, p, v in rows]
        names[catalog] = name
        print(f"{name} ({catalog}): TLE epoch {epoch:%Y-%m-%d %H:%M} UTC, {len(rows)} states")

    payload = {
        "epoch": start.strftime("%d %b %Y %H:%M:%S.000"),          # UTC; t = seconds after this
        "generated": now.strftime("%d %b %Y %H:%M:%S.000"),
        "generated_t": (now - start).total_seconds(),              # where "now" was at run time
        "names": names,
        "objects": objects,
    }
    OUT_JSON.write_text(json.dumps(payload))
    print(f"Wrote {OUT_JSON} (window {start:%Y-%m-%d %H:%M} to {end:%Y-%m-%d %H:%M} UTC)")


if __name__ == "__main__":
    main()
